export default {
  id: "opencode",
  priority: 40,
  hasFree: true,
  alias: "oc",
  uiAlias: "oc",
  display: {
    name: "OpenCode Free",
    icon: "terminal",
    color: "#E87040",
    textIcon: "OC",
  },
  category: "free",
  noAuth: true,
  transport: {
    baseUrl: "https://opencode.ai",
    headers: {
      "x-opencode-client": "desktop",
    },
    noAuth: true,
  },
  models: [
    { id: "glm-5.2-free", name: "GLM 5.2 Free" },
    { id: "glm-5.1-free", name: "GLM 5.1 Free" },
    { id: "kimi-k2.6-free", name: "Kimi K2.6 Free" },
    { id: "kimi-k2.5-free", name: "Kimi K2.5 Free" },
    { id: "minimax-m2.7-free", name: "MiniMax M2.7 Free" },
    { id: "minimax-m2.5-free", name: "MiniMax M2.5 Free" },
    { id: "qwen3.7-max-free", name: "Qwen 3.7 Max Free" },
    { id: "qwen3-max-free", name: "Qwen 3 Max Free" },
    { id: "qwen3.6-plus-free", name: "Qwen 3.6 Plus Free" },
    { id: "mimo-v2.5-free", name: "MiMo V2.5 Free" },
    { id: "deepseek-v4-pro-free", name: "DeepSeek V4 Pro Free" },
    { id: "big-pickle", name: "Big Pickle" },
  ],
  modelsFetcher: { url: "https://opencode.ai/zen/v1/models", type: "opencode-free" },
  passthroughModels: true,
};
