"use client";

import { useState, useSyncExternalStore } from "react";
import { Button } from "@/shared/components";
import { useCopyToClipboard } from "@/shared/hooks/useCopyToClipboard";

const shellQuote = (value) => `'${String(value).replaceAll("'", `'"'"'`)}'`;
const subscribe = () => () => {};
const getPlatform = () => {
  const value = navigator.userAgentData?.platform || navigator.platform || navigator.userAgent;
  if (/win/i.test(value)) return "windows";
  if (/mac/i.test(value)) return "mac";
  return "linux";
};

export default function BashSetupButton({
  tool,
  baseUrl,
  apiKey = "",
  model = "",
  smolModel = "",
  slowModel = "",
  planModel = "",
  modelRoles = null,
  models = [],
  variant = "secondary",
  className = "",
}) {
  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const platform = useSyncExternalStore(subscribe, getPlatform, () => "linux");
  const { copied, copy } = useCopyToClipboard();

  const handleDownload = async (format) => {
    setDownloading(true);
    setDownloaded(false);
    try {
      const response = await fetch(format === "bat" ? "/9router-connect.ps1" : "/9router-connect.sh");
      if (!response.ok) throw new Error("Failed to download installer");

      const source = await response.text();
      const apiUrl = baseUrl.endsWith("/v1") ? baseUrl : `${baseUrl}/v1`;
      let installer;
      let filename;
      let type;

      if (format === "bat") {
        const psQuote = (value) => `'${String(value).replaceAll("'", "''")}'`;
        let modelArgs = "";
        if (model) modelArgs += ` -Model ${psQuote(model)}`;
        if (smolModel) modelArgs += ` -SmolModel ${psQuote(smolModel)}`;
        if (slowModel) modelArgs += ` -SlowModel ${psQuote(slowModel)}`;
        if (planModel) modelArgs += ` -PlanModel ${psQuote(planModel)}`;
        if (modelRoles && typeof modelRoles === "object" && Object.keys(modelRoles).length > 0) {
          const rolesJson = JSON.stringify(modelRoles);
          const rolesB64 = typeof window !== "undefined" && window.btoa ? window.btoa(unescape(encodeURIComponent(rolesJson))) : Buffer.from(rolesJson).toString("base64");
          modelArgs += ` -ModelRolesBase64 ${psQuote(rolesB64)}`;
        }
        if (Array.isArray(models) && models.length > 0) {
          const modelsJoined = models.map((m) => psQuote(m)).join(",");
          modelArgs += ` -Models @(${modelsJoined})`;
        }
        const command = `$raw=[IO.File]::ReadAllText($env:NINEROUTER_INSTALLER); $marker='# 9ROUTER '+'POWERSHELL PAYLOAD'; $payload=$raw.Substring($raw.IndexOf($marker)+$marker.Length).TrimStart(); & ([ScriptBlock]::Create($payload)) -Tool ${psQuote(tool)} -BaseUrl ${psQuote(apiUrl)} -ApiKey ${psQuote(apiKey)}${modelArgs} -NoPrompt`;
        const batch = `@echo off\r\nsetlocal\r\ntitle 9Router ${tool} Installer\r\nset "NINEROUTER_INSTALLER=%~f0"\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -Command "${command}"\r\nset "EXIT_CODE=%ERRORLEVEL%"\r\necho.\r\nif not "%EXIT_CODE%"=="0" echo Installation failed with exit code %EXIT_CODE%.\r\npause\r\nexit /b %EXIT_CODE%\r\n\r\n# 9ROUTER POWERSHELL PAYLOAD\r\n`;
        installer = batch + source.replaceAll("\n", "\r\n");
        filename = `install-9router-${tool}.bat`;
        type = "application/x-bat";
      } else {
        let shModelArgs = "";
        if (model) shModelArgs += ` --model ${shellQuote(model)}`;
        if (smolModel) shModelArgs += ` --smol-model ${shellQuote(smolModel)}`;
        if (slowModel) shModelArgs += ` --slow-model ${shellQuote(slowModel)}`;
        if (planModel) shModelArgs += ` --plan-model ${shellQuote(planModel)}`;
        if (modelRoles && typeof modelRoles === "object" && Object.keys(modelRoles).length > 0) {
          shModelArgs += ` --model-roles ${shellQuote(JSON.stringify(modelRoles))}`;
        }
        if (Array.isArray(models) && models.length > 0) {
          shModelArgs += ` --models ${shellQuote(models.join(","))}`;
        }
        const generatedArgs = `set -- --tool ${shellQuote(tool)} --url ${shellQuote(apiUrl)} --api-key ${shellQuote(apiKey)}${shModelArgs} --no-prompt "$@"`;
        installer = source.replace(
          "SKIP_CHECK=0",
          `SKIP_CHECK=0\n\n# Generated by the 9Router Dashboard. Extra arguments can override these defaults.\n${generatedArgs}`
        );
        filename = format === "command" ? `install-9router-${tool}.command` : `install-9router-${tool}.sh`;
        type = "application/x-sh";
      }

      const blobUrl = URL.createObjectURL(new Blob([installer], { type }));
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(blobUrl);
      setDownloaded(true);
    } catch (error) {
      console.log("Error downloading 9Router installer:", error);
    } finally {
      setDownloading(false);
    }
  };

  const handleLinuxCommand = () => {
    const apiUrl = baseUrl.endsWith("/v1") ? baseUrl : `${baseUrl}/v1`;
    const serverUrl = apiUrl.slice(0, -3);
    let shModelArgs = "";
    if (model) shModelArgs += ` --model ${shellQuote(model)}`;
    if (smolModel) shModelArgs += ` --smol-model ${shellQuote(smolModel)}`;
    if (slowModel) shModelArgs += ` --slow-model ${shellQuote(slowModel)}`;
    if (planModel) shModelArgs += ` --plan-model ${shellQuote(planModel)}`;
    if (modelRoles && typeof modelRoles === "object" && Object.keys(modelRoles).length > 0) {
      shModelArgs += ` --model-roles ${shellQuote(JSON.stringify(modelRoles))}`;
    }
    if (Array.isArray(models) && models.length > 0) {
      shModelArgs += ` --models ${shellQuote(models.join(","))}`;
    }
    const command = `installer="$(mktemp)" && curl -fsSL ${shellQuote(`${serverUrl}/9router-connect.sh`)} -o "$installer" && bash "$installer" --tool ${shellQuote(tool)} --url ${shellQuote(apiUrl)} --api-key ${shellQuote(apiKey)}${shModelArgs} --no-prompt; status=$?; rm -f "$installer"; exit $status`;
    copy(command, `${tool}-linux-install`);
  };

  const primary = platform === "windows"
    ? { label: "Download Windows .bat", icon: "download", action: () => handleDownload("bat") }
    : platform === "mac"
      ? { label: "Download macOS .command", icon: "download", action: () => handleDownload("command") }
      : { label: copied === `${tool}-linux-install` ? "Copied - Run in Terminal" : "Copy Linux Install Command", icon: "terminal", action: handleLinuxCommand };

  return <div className="flex flex-wrap items-center gap-1.5">
    <Button variant={variant} size="sm" onClick={primary.action} loading={downloading} disabled={!apiKey} title={!apiKey ? "Create or select an API key first" : undefined} className={className}>
      <span className="material-symbols-outlined text-[16px] mr-1">{downloaded ? "check" : primary.icon}</span>
      {downloaded ? "Downloaded - Run File" : primary.label}
    </Button>
    {platform !== "windows" && <Button variant="ghost" size="sm" onClick={() => handleDownload("bat")} disabled={downloading || !apiKey}>Windows .bat</Button>}
    {platform !== "mac" && <Button variant="ghost" size="sm" onClick={() => handleDownload("command")} disabled={downloading || !apiKey}>macOS .command</Button>}
    {platform !== "linux" && <Button variant="ghost" size="sm" onClick={handleLinuxCommand} disabled={downloading || !apiKey}>Linux command</Button>}
  </div>;
}
